### ISSUE TITLE
Getting file name too long during build.

### ISSUE THREAD

**Issue by drewcsillag** [joekiller/logstash-kafka#9]
I'm unable to build the flatjar target.  I tried making my path that I'm building in as short as possible (/tmp/x), but I suspect the class name explosion bit is the real problem.

FWIW, I also tried building against Kafka 0.8.1 with differing Scala versions and got the same error.

```
find $PWD/v/bundle $PWD/v/jar -name '*.jar' \
    | (cd build/monolith; xargs -n1 /usr/lib/jvm/jdk1.7-oracle/bin/jar xf)
java.io.FileNotFoundException: scala/tools/nsc/backend/icode/analysis/ReachingDefinitions$ReachingDefinitionsAnalysis$$anonfun$scala$tools$nsc$backend$icode$analysis$ReachingDefinitions$ReachingDefinitionsAnalysis$$dropsAndGen$1.class (File name too long)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at sun.tools.jar.Main.copy(Main.java:808)
    at sun.tools.jar.Main.extractFile(Main.java:958)
    at sun.tools.jar.Main.extract(Main.java:877)
    at sun.tools.jar.Main.run(Main.java:263)
    at sun.tools.jar.Main.main(Main.java:1177)
java.io.FileNotFoundException: kafka/consumer/ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance$2$$anonfun$apply$10$$anonfun$apply$12.class (File name too long)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at sun.tools.jar.Main.copy(Main.java:808)
    at sun.tools.jar.Main.extractFile(Main.java:958)
    at sun.tools.jar.Main.extract(Main.java:877)
    at sun.tools.jar.Main.run(Main.java:263)
    at sun.tools.jar.Main.main(Main.java:1177)
make: *** [build/monolith] Error 123
```

**Comment by gamicklisafisher** [comment]
For copying and deleting “Long Path Tool” software should be try, many articles refer this for such solutions.
